version: "1"
rules:
  - base: main
    upstream: rngKomorebi/daplis:main
    mergeMethod: hardreset
    mergeUnstable: true    
  - base: develop
    upstream: rngKomorebi/daplis:develop       
    mergeMethod: hardreset
    mergeUnstable: true
  - base: gh-pages
    upstream: rngKomorebi/daplis:gh-pages
    mergeMethod: hardreset
    mergeUnstable: true
